sudo: false
language: python

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Test against multiple version of SciPy, with and without slycot
#
# Because there were significant changes in SciPy between v0 and v1, we 
# test against both of these using the Travis CI environment capability
#
# We also want to test with and without slycot
env:
  - SCIPY=0.19.1 SLYCOT=
  - SCIPY=0.19.1 SLYCOT=slycot
  - SCIPY=1.0.0 SLYCOT=

# install required system libraries
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # use miniconda to install numpy/scipy, to avoid lengthy build from source
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # conda-build must be installed in the conda root environment
  - conda install conda-build
  - conda config --add channels python-control
  - conda info -a
  - conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pip coverage
  - source activate test-environment
  # coveralls not in conda repos
  - pip install coveralls

# Install packages
install:
  # Install the desired version of SciPy first, w/ or w/out slycot
  - conda install scipy==$SCIPY $SLYCOT
  - conda install matplotlib
  # Don't use conda for installation of control library [preserves scipy]
  - python setup.py install

# command to run tests
script:
  - 'if [ $SLYCOT != "" ]; then python -c "import slycot"; fi'
  - coverage run setup.py test

after_success:
  - coveralls
